### ISSUE TITLE
cutouts

### ISSUE THREAD

**Issue by mcoughlin** [karpov-sv/stdpipe#10]
It would be nice if there was an option to overlay a circular aperture indicating the object in the center of the cutout.

**Comment by karpov-sv** [comment]
There is already a set of options for overlaying a circle onto all cutouts in `plot_cutout()` - `mark_x`, `mark_y`, `mark_r`. Currently it only works in pixel coordinates, and the color/linewidth are hardcoded. Do you need more configurability for it?

**Comment by karpov-sv** [comment]
A bit more control added in 081ba9aa9448bc0e4675a52ef1fdb16e9c8d9f99

**Comment by mcoughlin** [comment]
It's great, thanks @karpov-sv
