### ISSUE TITLE
bg_mask.multiply(image1) 

### ISSUE THREAD

**Issue by mcoughlin** [karpov-sv/stdpipe#8]
https://github.com/karpov-sv/stdpipe/blob/master/stdpipe/photometry.py#L806

I get:

    bg_vals = bg_mask.multiply(image1)[bg_mask.data > 0]
TypeError: 'NoneType' object is not subscriptable

I know it works sometimes, but should do some handling, i.e. check that bg_mask.multiply(image1) is not None and then get the array.

**Comment by karpov-sv** [comment]
Care to provide specific use case when this error is triggered?..

**Comment by karpov-sv** [comment]
_Hopefully_ fixed in c89152decb6664896b0bc614f5eeed52816ab27f, please check.

**Comment by mcoughlin** [comment]
@karpov-sv yes it passed, thanks!
